### ISSUE TITLE
OIAA Meeting Directory Down

### ISSUE THREAD

**Issue by MarkM2728** [code4recovery/central#16]
User reported error confirmed.
Directory displays error: **TypeError: Failed to Fetch**

I then went into central and tried making an update to a group.
Received the following error:
**File storage error: connect: getConnection: Timed out while waiting for handshake**

**Comment by joshreisner** [comment]
in order to help with this, we need to figure out what's causing it. it would help if we could 
construct a timeline of what happened, could you help with this @MarkM2728 ?

looks like this was reported at 4:21 am PST

when I saw the issue at 5:37am PST the issue was resolved

looking at the history:
<img width="873" alt="Screenshot 2024-03-09 at 6 46 18 AM" src="https://github.com/code4recovery/central/assets/1551689/ef3fe553-2a17-4333-bb9b-852d7560811c">

here are some guesses:
* looks like you made edits at 4:13 and 4:57 - i'm assuming these were trying to fix the issue but the FTP connection was unsuccessful?
* guessing the edit later at 4:59 fixed it (this user made more edits after)
* the previous edit / FTP write was about 24 hours earlier, and assuming that this wasn't the one that broke the meeting finder

please let me know if i'm missing anything, because going by this it seems like something on the remote server could have messed up the JSON file there independently of an action by Central

also another thing we learn today is that sometimes the FTP server doesn't want to accept incoming connections, which is concerning

**Comment by MarkM2728** [comment]
I first saw the issue reported at 6:11am cst.   Correct, the 4:13am edit (6:13am cst) was my trying fix the issue by making an update and I received the FTP connection error.

4:57 edit was unsuccessful.

I make the same assumption, that the last edit (removing a group representative) did not break it.

at 4:59, Keri R was making successful updates

**Comment by joshreisner** [comment]
great, thanks Mark. we'll discuss it in the Code 4 Recovery meeting today and come up with some solution

**Comment by joshreisner** [comment]
hi @MarkM2728 going forward, updates in central will no longer automatically trigger a FTP write. to update the list, visit http://data.aa-intergroup.org/ in your browser and the list will be refreshed

this should improve reliability in the short term until a new solution can be found. i know @mattbylett @tim-rohrer and others are working on solutions. also there is a member @ginslo who may be able to help the team set up automated uptime monitoring

judging by the chart above, our best guess is the whole server was unavailable during the downtime window last night, and this particlar downtime looks like it wasn't related to FTP issues we've been having
