### ISSUE TITLE
Editing Representatives

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/central#24]
Hi Jeff B from OIAA, 

In Central, if I edit a reps email, save it, I see the new email in the field.  If I refresh Json and refresh Central, the old email still appears. 
I thought this worked previously, but I've been deleting the rep and adding the new info to make it work. 
Is my sequence out of order? thank you, Jeff

**Comment by mattbylett** [comment]
Hey Jeff

Sorry for the delay buddy - I’ll have a look into this today for you and
let you know how I get on

Is it still an issue for you ?

We help businesses develop integrated ecommerce digital solutions

Matthew Bylett
Founder Think New Ltd
022 029 2881

**Comment by twn2twn** [comment]
Yes it's always been a little screwy but I thought that it worked at one
time where I could edit a representative and then sometimes refresh the
page to have it stick other times refresh Jason or a combination of those
but it's not working now

**Comment by mattbylett** [comment]
Ok no worries- I got a new system so I have to get set up locally again but
I’ll get that done and investigate… give me a few hours :)

More soon

We help businesses develop integrated ecommerce digital solutions

Matthew Bylett
Founder Think New Ltd
022 029 2881

**Comment by mattbylett** [comment]
Hey Jeff

I'm just looking into this issue and I decided to play around with my home
group which is NZ Daily Zoom into the World of the Spirit
<https://central.aa-intergroup.org/groups/648e50e5b291ed6c5135f0a2>

Now, it appears that we are down as 7 individual meetings and not a group -
Is that correct?

I say this because when I search it says 7 meetings and when I click that
lets me edit the meeting but of course there is no where for me to add /
edit a representative at meeting level

So I guess the question is - do we have a group in central?

If not can I add one while I troubleshoot this error

Many thanks in advance

Matt

**Comment by twn2twn** [comment]
Ill look when I'm home and have access. Thank you

**Comment by mattbylett** [comment]
Hi Jeff,

Please disregard the last message - I've got that sored and was indeed able
to make a change to representatives for our group.

I don't understand the problem you are having though - please can you let
me know exactly what steps you are taking and what's going wrong.

This is what I did:

   - In Central, Searched for Group : NZ Daily WOS
   - Edited Representative: Replaced David (who no Longer attends) with My
   contact Details
   - Went to http://data.aa-intergroup.org/refresh to refresh the json feed
   - Checked Central expecting My change to no longer be there
   - My change is still in place and I am still representing the group
   - Logged out of Central, Logged back in - the change is still active


Please clarify if I have mis-understood the problem

Many thanks Matt

**Comment by joshreisner** [comment]
hey @twn2twn so i'd forgotten the context on this issue, exactly a year ago this came up, and the team at the time decided that what they wanted here was to disable editing the email address of group representatives. reps can still be added and removed.

the reason is that reps can and often do represent more than one meeting. these are linked in the backend so that (eventually) people will be able to log in and request changes to their meetings. if we allow editing at the group's level it's not clear if this change only applies to this group, or all the groups that this user represents.

i actually had code in a [pull request](https://github.com/code4recovery/central/pull/10) just waiting for a year, but it's merged now.

hope that's clear and makes sense. going to close this for now but we can discuss it in the next meeting if there's an improvement that can be made here
